name: Build PS1 Homebrew
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache GCC Toolchain
        id: cache-gcc
        uses: actions/cache@v3
        with:
          path: gcc-mipsel-none-elf
          key: ${{ runner.os }}-gcc-mips-16.1.0

      - name: Build Toolchain (Only if not cached)
        if: steps.cache-gcc.outputs.cache-hit != 'true'
        run: |
          chmod +x .github/scripts/buildToolchain.sh
          ./.github/scripts/buildToolchain.sh
          
      - name: Install Python Dependencies
        run: |
          python3 -m pip install Pillow
          
      - name: Build and Inject Demo
        run: |
          export PATH=$PATH:$(pwd)/gcc-mipsel-none-elf/bin
          chmod +x .github/scripts/buildRelease.sh
          ./.github/scripts/buildRelease.sh